services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: horno-comarca:1.0
    container_name: horno-web
    environment:
      PORT: "3000"
      REDIS_URL: redis://redis:6379
      STUDENT_NAME: ${STUDENT_NAME:-Estudiante}
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - horno-red

  redis:
    image: redis:7-alpine
    container_name: horno-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - horno-red

volumes:
  redis-data:
    name: horno-redis-data

networks:
  horno-red:
    name: horno-red
    driver: bridge
